Class {
	#name : #Amqp091ExchangeDeclareOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Ansible-Protocol-091'
}

{ #category : #'AMQP codec' }
Amqp091ExchangeDeclareOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp091ExchangeDeclareOk >> codecMethodId [

	^ 2621451
]

{ #category : #'AMQP codec' }
Amqp091ExchangeDeclareOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091ExchangeDeclareOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091ExchangeDeclareOk >> hasContents [

	^ false
]
