Class {
	#name : #Amqp091BasicQosOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Ansible-Protocol-091'
}

{ #category : #'AMQP codec' }
Amqp091BasicQosOk >> acceptableResponseClasses [

	^ #()
]

{ #category : #'AMQP codec' }
Amqp091BasicQosOk >> codecMethodId [

	^ 3932171
]

{ #category : #'AMQP codec' }
Amqp091BasicQosOk >> decodeFrom: codec [

	
]

{ #category : #'AMQP codec' }
Amqp091BasicQosOk >> encodeOn: codec [

	
]

{ #category : #'AMQP codec' }
Amqp091BasicQosOk >> hasContents [

	^ false
]
