Class {
	#name : #Amqp091BasicRecoverOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Ansible-Protocol-091'
}

{ #category : #'AMQP codec' }
Amqp091BasicRecoverOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp091BasicRecoverOk >> codecMethodId [

	^ 3932271
]

{ #category : #'AMQP codec' }
Amqp091BasicRecoverOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091BasicRecoverOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091BasicRecoverOk >> hasContents [

	^ false
]
