Class {
	#name : #Amqp091QueueBindOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Amqp-Protocol-091'
}

{ #category : #'AMQP codec' }
Amqp091QueueBindOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp091QueueBindOk >> codecMethodId [

	^ 3276821
]

{ #category : #'AMQP codec' }
Amqp091QueueBindOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091QueueBindOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp091QueueBindOk >> hasContents [

	^ false
]
