Class {
	#name : #Amqp08StreamQosOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Amqp-Protocol-08'
}

{ #category : #'AMQP codec' }
Amqp08StreamQosOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp08StreamQosOk >> codecMethodId [

	^ 5242891
]

{ #category : #'AMQP codec' }
Amqp08StreamQosOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08StreamQosOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08StreamQosOk >> hasContents [

	^ false
]
