Class {
	#name : #Amqp08FileQosOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Amqp-Protocol-08'
}

{ #category : #'AMQP codec' }
Amqp08FileQosOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp08FileQosOk >> codecMethodId [

	^ 4587531
]

{ #category : #'AMQP codec' }
Amqp08FileQosOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08FileQosOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08FileQosOk >> hasContents [

	^ false
]
