Class {
	#name : #Amqp08BasicQosOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Amqp-Protocol-08'
}

{ #category : #'AMQP codec' }
Amqp08BasicQosOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp08BasicQosOk >> codecMethodId [

	^ 3932171
]

{ #category : #'AMQP codec' }
Amqp08BasicQosOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08BasicQosOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08BasicQosOk >> hasContents [

	^ false
]
