Class {
	#name : #Amqp08ExchangeDeclareOk,
	#superclass : #AmqpProtocolMethod,
	#category : #'Amqp-Protocol-08'
}

{ #category : #'AMQP codec' }
Amqp08ExchangeDeclareOk >> acceptableResponseClasses [

	^ {}
]

{ #category : #'AMQP codec' }
Amqp08ExchangeDeclareOk >> codecMethodId [

	^ 2621451
]

{ #category : #'AMQP codec' }
Amqp08ExchangeDeclareOk >> decodeFrom: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08ExchangeDeclareOk >> encodeOn: codec [

	| bitBuffer |

	
]

{ #category : #'AMQP codec' }
Amqp08ExchangeDeclareOk >> hasContents [

	^ false
]
